### ISSUE TITLE
Add trading volume tracking page

### ISSUE THREAD

**Issue by chefchansey** [Ditto-money/dashboard#3]
Integrate the  [volume tracking dapp](https://dittoscan.netlify.app/) into the dashboard. Update the styling to match the rest of the dashboard.

## Overview

@Timidan has developed a volume tracker that we have already successfully used in one trading competition. The goal of this bounty is to polish the tracker to perfection and integrate it with our dashboard.

The current version is found here:

https://dittoscan.netlify.app/

Github repo:

[DIttoScan](https://github.com/Ditto-money/DIttoScan)

## Details

- Add a new subsection titled "Trading volume tool" on the [DITTO Money dashboard](https://ditto.money/dashboard/)
- Like in the [standalone version](https://dittoscan.netlify.app/) it should be possible to select a range of blocks and get the volume per address in return (list sorted by volume)
- **The result should not include smart contracts**
- Improve usability such that it is clear to the user that there is a maximum range of blocks that's supported, or improve the app to support a longer range. 
- Deploy the final version on our webserver.

## Contact Information

We are looking for an *experienced* frontend developer who can do this job independently. If you get approved for this bounty contact @chefchansey on the DITTO Telegram channel:

https://t.me/dittomoney

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.5 ETH (882.98 USD @ $1765.96/ETH)  attached to it as part of the Ditto Money fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,026,401.56 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 9 months from now.
Please review their action plans below:


**1) [gemasphi](https://gitcoin.co/gemasphi) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?mutate_worker_action=approve&worker=gemasphi) | [reject worker](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?mutate_worker_action=reject&worker=gemasphi))_.**

I think I am experienced enough to do this task.

My action plan would be:
- Understand the volume tracking app API
- Based on the API, add the features in the Details
- Match the styling to the rest of the dashboard
- Deploy it
**2) [qwertasio](https://gitcoin.co/qwertasio) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?mutate_worker_action=approve&worker=qwertasio) | [reject worker](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?mutate_worker_action=reject&worker=qwertasio))_.**

Retrieve data from api 
Filter it to make it presentable according to requirements
Deploy on webserver
**3) [bdkma95](https://gitcoin.co/bdkma95) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?mutate_worker_action=approve&worker=bdkma95) | [reject worker](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?mutate_worker_action=reject&worker=bdkma95))_.**

I have build a Blockchain, created cryptocurrency (Bcoin) and smart contracts by using Solidity. I know how to use Python, Flask, JSON, Truffle(Remix), Anaconda, Docker, Postman(API), Ubuntu, Visual studio code, Pycharm, Nodejs, React, MyEtherWallet, GitHub and Django.
**4) [mul53](https://gitcoin.co/mul53) has been approved to start work.**

Hi, I have worked on various frontend projects and completed several frontend bounties so i'm confident of completing the task. I also have experience deploying frontend clients. I will do the work in the least of time possible. Thanks
**5) [arbreton](https://gitcoin.co/arbreton) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?mutate_worker_action=approve&worker=arbreton) | [reject worker](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?mutate_worker_action=reject&worker=arbreton))_.**

I have worked for a year in DAPP dev before, the request is pretty simple

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746).

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by mul53** [comment]
@gitcoinbot working on the issue

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by mul53** [comment]
@gitcoinbot Yes I will submit a PR in a few days

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by mul53** [comment]
@gitcoinbot working on it and made some progress will have a pr on Monday or Tuesday

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by mul53** [comment]
@gitcoinbot added a draft PR

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by mul53** [comment]
@gitcoinbot Still working on this

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by gitcoinbot** [comment]
@mul53 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=1) | [3 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=3) | [5 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=5) | [10 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=10) | [100 days](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 0.5 ETH (888.96 USD @ $1777.91/ETH) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/Ditto-money/dashboard/3/100024746).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,508,388.34 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
